### ISSUE TITLE
Rohdaten cannot be deleted anymore

### ISSUE THREAD

**Issue by tone2tone** [CONTENIDO/CONTENIDO#496]
The actual dev version (today 2024-07-26 and some versions back, minimum from Feb 2024 onwards) are not working anymore when trying to delete a CMS element from "Rohdaten" tab. The confirmation popup comes up when pressing the delete button, but no action is executed after confirming the popup request. Tested under Win11 and in various browsers (Chrome, FF, Edge).

**Comment by muratpurc** [comment]
@tone2tone thank you for the bug report, it has been fixed.

**Comment by tone2tone** [comment]
Hi Murat, sorry to say the problem doesn't seem to be solved. I downloaded the new dev, but the two new files do not change the behaviour. I am still not able to delete cms-content-types from the raw data section. After the popup with the "confirm delete" appears, still nothing happens afterwards.

**Comment by muratpurc** [comment]
@tone2tone thank you for your feedback, the issue has been reopened.

**Comment by dceonline** [comment]
Please checkout new pull request #502

**Comment by tone2tone** [comment]
Thank you guys! Checked it with the new version and it is working now. :-)
